export const data = {
  entities: {
    users: [
      { id: 11, name: 'Uday' },
      { id: 12, name: 'Nitin' },
    ],
    orgs: [
      { id: 1, name: 'HDFC' },
      { id: 2, name: 'Rapido' },
      { id: 3, name: 'HDFC2' },
      { id: 4, name: 'Rapido2' },
      { id: 5, name: 'HDFC3' },
      { id: 6, name: 'Rapido3' },
      { id: 7, name: 'HDFC4' },
      { id: 8, name: 'Rapido4' },
      { id: 9, name: 'HDFC5' },
      { id: 10, name: 'Rapido5' },
    ],
  },
  categories: [
    { id: 1, name: 'Food' },
    { id: 2, name: 'Travel' },
  ],
  transactions: {
    expense: [
      {
        id: '1',
        source: 'Swiggy',
        category: 'Food',
        amount: 1000,
        date: new Date(),
        description: 'Biriyani',
      },
      {
        id: '2',
        source: 'Swiggy',
        category: 'Food',
        amount: 1000,
        date: new Date(),
        description: 'Biriyani',
      },
      {
        id: '3',
        source: 'Swiggy',
        category: 'Food',
        amount: 1000,
        date: new Date(),
        description: 'Biriyani',
      },
      {
        id: '4',
        source: 'Swiggy',
        category: 'Food',
        amount: 1000,
        date: new Date(),
        description: 'Biriyani',
      },
      {
        id: '5',
        source: 'Swiggy',
        category: 'Food',
        amount: 1000,
        date: new Date(),
        description: 'Biriyani',
      },
      {
        id: '6',
        source: 'Swiggy',
        category: 'Food',
        amount: 1000,
        date: new Date(),
        description: 'Biriyani',
      },
      {
        id: '7',
        source: 'Swiggy',
        category: 'Food',
        amount: 1000,
        date: new Date(),
        description: 'Biriyani',
      },
      {
        id: '8',
        source: 'Swiggy',
        category: 'Food',
        amount: 1000,
        date: new Date(),
        description: 'Biriyani',
      },
      {
        id: '9',
        source: 'Swiggy',
        category: 'Food',
        amount: 1000,
        date: new Date(),
        description: 'Biriyani',
      },
      {
        id: '10',
        source: 'Swiggy',
        category: 'Food',
        amount: 1000,
        date: new Date(),
        description: 'Biriyani',
      },
      {
        id: '11',
        source: 'Swiggy',
        category: 'Food',
        amount: 1000,
        date: new Date(),
        description: 'Biriyani',
      },
      {
        id: '12',
        source: 'Swiggy',
        category: 'Food',
        amount: 1000,
        date: new Date(),
        description: 'Biriyani',
      },
      {
        id: '13',
        source: 'Swiggy',
        category: 'Food',
        amount: 1000,
        date: new Date(),
        description: 'Biriyani',
      },
    ],
    income: [
      {
        id: '2',
        source: 'ClearTax',
        category: 'Salary',
        amount: 100000,
        date: new Date(),
        description: 'Salary',
      },
    ],
  },
}
